name: Deployment Produto MS WEB

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        environment: LCWB_SH_PRD
        steps:
        - uses: actions/checkout@v2

        - name: Setup Env Node
          uses: actions/setup-node@v1
          with:
              node-version: 19

        - name: Instalando lib package.json
          run: npm ci

        - name: Criando .env.production
          run: |
            touch .env.production
            NODE_ENV="production" >> .env.production
            REACT_APP_HOST_API=${{ secrets.REACT_APP_HOST_API }} >> .env.production
            cat .env.production

        - name: Criando .env
          run: |
            touch .env
            NODE_ENV="production" >> .env
            REACT_APP_HOST_API=${{ secrets.REACT_APP_HOST_API }} >> .env
            cat .env

        - name: Iniciando Build
          run: npm run build:prod
          env:
            REACT_APP_HOST_API: ${{ secrets.REACT_APP_HOST_API }}

        - name: Sync Files
          uses: SamKirkland/FTP-Deploy-Action@4.3.3
          with:
              server: ${{ secrets.FTP_HOST }}
              username: ${{ secrets.FTP_USER }}
              password: ${{ secrets.FTP_PWD }}
              server-dir: public_html/
              local-dir: ./build/
